##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

###########################################################
# Database Settings
##########################################################
app.datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springapp_db
    username: springapp_user
    password: ENC(CM64Uxs+V8Ri4nrKnMGfyw==)
    maxPoolSize: 10

development.mode: true

network: NIPR

###########################################################
# Password Encryption
##########################################################
jasypt:
    encryptor:
        algorithm: PBEWithMD5AndDES
        password: 'ab5823423464j1k2#!!6298-+'

###########################################################
# ElasticSearch Settings
##########################################################

es.url: http://localhost:9200