##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

###########################################################
# Database Settings
##########################################################
app.datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springapp_db
    username: springapp_user
    password: secret
    maxPoolSize: 10